# Generated by Django 2.1.7 on 2019-03-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0005_auto_20190322_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testament',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Partner'),
        ),
    ]
