# Generated by Django 2.1.7 on 2019-03-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0008_auto_20190322_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testament',
            old_name='partner',
            new_name='name',
        ),
    ]
