# Generated by Django 2.1.7 on 2019-03-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0009_auto_20190322_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testament',
            old_name='name',
            new_name='author',
        ),
    ]
