# Generated by Django 2.1.7 on 2019-03-22 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0010_auto_20190322_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testament',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
