# Generated by Django 2.1.7 on 2019-03-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testaments', '0011_auto_20190322_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testament',
            old_name='author',
            new_name='user',
        ),
    ]
